/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StableSwap3Pool } from "./StableSwap3Pool";
export type { StableSwapFactoryPool } from "./StableSwapFactoryPool";
